
export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_SUCCES = 'POST_USER_SUCCESS';
export const POST_USER_FAILED = 'POST_USER_FAILED';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_STATUS_REQUEST = 'SET_STATUS_REQUEST';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';

export const FARGOT_PASSWORD_SUCCESFLY = 'FARGOT_PASSWORD_SUCCESFLY';

export const FARGOT_PASSWORD_REQUEST = 'FARGOT_PASSWORD_REQUEST';

export const FARGOT_PASSWORD_FAILED = 'FARGOT_PASSWORD_FAILED';

export const SET_FARGOT_CHECKED = 'SET_FARGOT_CHECKED';

export const SET_LOGIN_CHECKED = 'SET_LOGIN_CHECKED';

export const RESET__PASSWORD_SUCCESSFLY = 'RESET_PASSWORD_SUCCESSFLY';

export const RESET__PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
